apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: horizon-ingress
  namespace: openstack
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: horizon.brilliant.com.bd
    http:
      paths:
      - path: /
        backend:
          serviceName: horizon-int
          servicePort: 80
